export const styles = {
  avatar: {
    height: 38,
    width: 38,
    marginLeft: 15,
    cursor: 'pointer',
    backgroundColor: '#EEBC1D',
  },
  container: {
    width: 350,
    padding: 25,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  profile: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    height: '92%',
  },
  profilePicture: {
    width: 200,
    height: 200,
    cursor: 'pointer',
    backgroundColor: '#EEBC1D',
    objectFit: 'contain',
  },
  profileName: {
    width: '100%',
    fontSize: 22,
    textAlign: 'center',
    fontWeight: 'bolder',
    wordWrap: 'break-word',
  },
  watchlist: {
    flex: 1,
    width: '100%',
    backgroundColor: 'grey',
    borderRadius: 10,
    padding: 15,
    paddingTop: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    overflowY: 'scroll',
  },
  watchlistTitle: {
    fontSize: 15,
    textShadow: '0 0 5px black',
  },
  watchlistDeleteIcon: {
    cursor: 'pointer',
    marginTop: -4,
  },
  watchlistCoinContainer: {
    padding: 10,
    borderRadius: 5,
    color: 'black',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#EEBC1D',
    boxShadow: '0 0 3px black',
  },
  watchlistCoinInnerContainer: {
    display: 'flex',
    gap: 8,
  },
};
